# Generated by Django 3.2.13 on 2022-07-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorpattern',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
