# Generated by Django 3.2.13 on 2022-07-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20220728_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedindicator',
            name='npi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nota ponderada do indicador'),
        ),
        migrations.AddField(
            model_name='calculatedindicator',
            name='result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='calculatedindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_indicators', to='indicator.indicator', verbose_name='indicador'),
        ),
    ]
