# Generated by Django 3.2.13 on 2022-05-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador1',
            name='dt_avaliacao_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador1',
            name='dt_avaliacao_ini',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador1',
            name='quadrimestre',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
