
# Generated by Django 3.2.13 on 2022-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='numerador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
