# Generated by Django 3.2.13 on 2022-05-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_indicador_numerador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='indicador',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
