
# Generated by Django 3.2.13 on 2022-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_indicador_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='status',
            field=models.CharField(choices=[('1', 'Gerado'), ('2', 'Calculando'), ('3', 'Removido')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
