
# Generated by Django 3.2.13 on 2022-06-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_indicador1dados_indicador1dadosconsultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador1dadosconsultas',
            name='gestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador1dados'),
        ),
    ]
