# Generated by Django 3.2.13 on 2022-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_indicador1dadosconsultas_gestante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador1dados',
            name='cns',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='indicador1dados',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='indicador1dados',
            name='nome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
