# Generated by Django 3.2.13 on 2022-07-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220626_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Indicador 1 - Proporção de gestantes com pelo menos 6 (seis) consultas pré-natal realizadas, sendo a 1ª até a 12ª semana de gestação'), ('2', 'Indicador 2 - Proporção de gestantes com realização de exames para sífilis e HIV;'), ('3', 'Indicador 3 - Proporção de gestantes com atendimento odontológico realizado'), ('4', 'Indicador 4 - Proporção de mulheres com coleta de citopatológico na APS'), ('5', 'Indicador 5 - Proporção de crianças de 1(um) ano de idade vacinadas na APS contra Difeteria, Tétano, Coqueluche, Hepatite B, Infecções causadas por Haemophilus Influenzae tipo b e Poliomielite Inativada'), ('6', 'Indicador 6 - Proporção de pessoas com hipertensão, com consulta e pressão arterial aferida no semestre'), ('7', 'Indicador 7 - Proporção de pessoas com diabetes, com consulta e hemoglobina glicada solicitada no semestre')], max_length=1, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descrição')),
                ('denominator', models.IntegerField(verbose_name='denominador')),
                ('numerator', models.IntegerField(verbose_name='numerador')),
                ('indicator', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='indicador')),
                ('quadrimester', models.CharField(blank=True, max_length=7, verbose_name='quadrimestre')),
                ('dt_init_evaluation', models.DateField(blank=True, null=True, verbose_name='data inicial da avaliação')),
                ('dt_end_evaluation', models.DateField(blank=True, null=True, verbose_name='data final da avaliação')),
                ('status', models.CharField(choices=[('1', 'Gerado'), ('2', 'Calculando'), ('3', 'Removido')], max_length=1)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='calculada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicatorAppointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(verbose_name='ID do atendimento')),
                ('date', models.DateField(verbose_name='data')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='nome')),
                ('cns', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('dum', models.DateField(blank=True, null=True, verbose_name='data da última menstruação')),
                ('dpp', models.DateField(blank=True, null=True, verbose_name='data provável de parto')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicator', verbose_name='indicador')),
            ],
            options={
                'verbose_name': 'Dado do Indicador',
                'verbose_name_plural': 'Dados do Indicador',
            },
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
        migrations.DeleteModel(
            name='Indicador1',
        ),
        migrations.DeleteModel(
            name='Indicador1Dados',
        ),
        migrations.DeleteModel(
            name='Indicador1DadosConsultas',
        ),
        migrations.AddField(
            model_name='indicatorappointmentdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_appointments_set', to='core.indicatordata', verbose_name='pessoa'),
        ),
    ]
