# Generated by Django 3.2.13 on 2022-07-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220704_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[('1', 'Indicador 1 - Proporção de gestantes com pelo menos 6 (seis) consultas pré-natal realizadas, sendo a 1ª até a 12ª semana de gestação'), ('2', 'Indicador 2 - Proporção de gestantes com realização de exames para sífilis e HIV'), ('3', 'Indicador 3 - Proporção de gestantes com atendimento odontológico realizado'), ('4', 'Indicador 4 - Proporção de mulheres com coleta de citopatológico na APS'), ('5', 'Indicador 5 - Proporção de crianças de 1(um) ano de idade vacinadas na APS contra Difeteria, Tétano, Coqueluche, Hepatite B, Infecções causadas por Haemophilus Influenzae tipo b e Poliomielite Inativada'), ('6', 'Indicador 6 - Proporção de pessoas com hipertensão, com consulta e pressão arterial aferida no semestre'), ('7', 'Indicador 7 - Proporção de pessoas com diabetes, com consulta e hemoglobina glicada solicitada no semestre')], max_length=1, verbose_name='tipo'),
        ),
    ]
