# Generated by Django 3.2.13 on 2022-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220727_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ibge_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='código IBGE'),
        ),
    ]
