# Generated by Django 3.2.13 on 2022-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_address_appointment_healthunit_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthunit',
            name='esus_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='street',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
