# Generated by Django 3.2.13 on 2022-10-20 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20221019_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esus_code', models.BigIntegerField(blank=True, null=True, verbose_name='Código ESUS')),
                ('ine', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Equipe de Saúde',
                'verbose_name_plural': 'Equipes de Saúde',
            },
        ),
        migrations.AlterModelOptions(
            name='healthunit',
            options={'verbose_name': 'Unidade de Saúde', 'verbose_name_plural': 'Unidades de Saúde'},
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='complement',
            field=models.CharField(blank=True, max_length=25, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='esus_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código ESUS'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='number',
            field=models.CharField(blank=True, max_length=25, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='healthunit',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rua'),
        ),
    ]
