# Generated by Django 3.2.13 on 2022-10-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20221019_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthteam',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Cidade'),
        ),
    ]
