# Generated by Django 3.2.13 on 2022-10-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_healthteam_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='abortion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='esus_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código ESUS'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthteam'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthunit'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional_appointments', to='core.role'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
        migrations.AddField(
            model_name='role',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AddField(
            model_name='role',
            name='esus_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código ESUS'),
        ),
        migrations.AddField(
            model_name='role',
            name='health_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthteam'),
        ),
        migrations.AddField(
            model_name='role',
            name='health_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthunit'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paciente'), (2, 'Profissional')]),
        ),
    ]
