# Generated by Django 3.2.13 on 2022-10-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_auto_20220728_2143'),
        ('core', '0022_auto_20221028_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='indicator',
            field=models.ManyToManyField(to='indicator.CalculatedIndicator'),
        ),
    ]
