# Generated by Django 3.2.13 on 2022-11-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20221119_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('O', 'Odontologica'), ('M', 'Medica')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
