# Generated by Django 3.2.13 on 2022-12-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
