# Generated by Django 3.2.13 on 2023-01-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_child_diabetic_hypertensive_patientprocedure_procedure_woman'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='individual_register',
            field=models.BooleanField(default=True),
        ),
    ]
