# Generated by Django 3.2.13 on 2023-01-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_patientindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprocedure',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
