# Generated by Django 3.2.13 on 2023-02-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230214_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esus_id', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esus_id', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='profissional',
            new_name='professional',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_appointments', to='core.role'),
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='ciaps',
            new_name='ciaps_2',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='cids',
            new_name='cids_2'
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='cbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cbo'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='health_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthteam'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='health_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthunit'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_procedures', to='core.role'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='cbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cbo'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='health_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthteam'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='health_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthunit'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_vaccinations', to='core.role'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ciaps',
            field=models.ManyToManyField(to='core.CIAP'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cids',
            field=models.ManyToManyField(to='core.CID'),
        ),
    ]
