from .cadastros import (TbAdModalidade, TbAgendado, TbAtend, TbAtendProf,
                        TbAtendProfTipoEncamIntrn, TbAtor, TbCbo,
                        TbCdsTipoCuidador, TbCid10, TbCidadao,
                        TbClasseImunobiologico, TbClassificacaoRisco,
                        TbConselhoClasse, TbDoseImunobiologico, TbEquipe,
                        TbEscolaridade, TbEstadoCivil, TbEstrategiaVacinacao,
                        TbEtnia, TbImunobiologico, TbImunobiologicoLote,
                        TbLocalAplVacina, TbLocalAtend, TbLocalidade,
                        TbLotacao, TbMotivoReserva, TbNacionalidade, TbOrigem,
                        TbPais, TbProf, TbProntuario, TbRacaCor,
                        TbRacionalidadeSaude, TbRegistroVacinacao, TbSexo,
                        TbSituacaoAgendado, TbSituacaoLocalidade,
                        TbStatusAtend, TbStatusAtendProf,
                        TbSubtipoUnidadeSaude, TbTipoAgravo, TbTipoAtend,
                        TbTipoAtendProf, TbTipoEncamInterno, TbTipoEquipe,
                        TbTipoLocalidade, TbTipoLogradouro,
                        TbTipoRegistroVacinacao, TbTipoUnidadeSaude, TbUf,
                        TbUnidadeSaude, TbUsuario, TbVacinacao, TbViaAdmVacina)
from .cds import (TbCdsAleitamentoMaterno, TbCdsAtendIndividual,
                  TbCdsFichaAtendIndividual, TbCdsPic, TbCdsProf, TbCdsTurno)
from .dimensoes import (TbDimAleitamento, TbDimCbo, TbDimCiap, TbDimCid,
                        TbDimDoseImunobiologico, TbDimEquipe,
                        TbDimEstrategiaVacinacao, TbDimEtnia, TbDimFaixaEtaria,
                        TbDimFrequenciaAlimentacao, TbDimGrupoAtendimento,
                        TbDimIdentidadeGenero, TbDimImunobiologico,
                        TbDimLocalAtendimento, TbDimModalidadeAd,
                        TbDimMunicipio, TbDimNacionalidade, TbDimPais,
                        TbDimPovoComunidadTrad, TbDimProcedimento,
                        TbDimProfissional, TbDimRacaCor,
                        TbDimRacionalidadeSaude, TbDimSexo,
                        TbDimSituacaoTrabalho, TbDimTempo,
                        TbDimTempoMoradorRua, TbDimTipoAtendimento,
                        TbDimTipoCondicaoPeso, TbDimTipoConsultaOdonto,
                        TbDimTipoEscolaridade, TbDimTipoFicha,
                        TbDimTipoOrientacaoSexual, TbDimTipoOrigem,
                        TbDimTipoOrigemDadoTransp, TbDimTipoParentesco,
                        TbDimTipoSaidaCadastro, TbDimTurno, TbDimUf,
                        TbDimUnidadeSaude)
from .fatos import (TbFatAtdIndExames, TbFatAtdIndProblemas,
                    TbFatAtdIndProcedimentos, TbFatAtendimentoIndividual,
                    TbFatAtendimentoOdonto, TbFatAtendOdontoProblemas,
                    TbFatCadIndividual, TbFatCidadaoPec, TbFatProcedAtend,
                    TbFatProcedAtendProced, TbFatProcedimento,
                    TbFatRelOpGestante, TbFatVacinacao, TbFatVacinacaoVacina)
